\newlabel{chap:abstract}
\newlabel{chap:background}
\newlabel{chap:c++}
\newlabel{chap:conclusion}
\newlabel{chap:introduction}
\newlabel{chap:kokkosBackend}
\newlabel{chap:kokkosEMA}
\newlabel{chap:kokkosPM}
\newlabel{chap:related}
\newlabel{chap:tutorial}
\newlabel{fig:SemCaptureKokkos}
\newlabel{fig:execspace}
\newlabel{fig:memspace}
\newlabel{fig:parallelForAndReduceKokkos}
\newlabel{fig:spaces}
\newlabel{fig:stack}
\newlabel{figKokkosLike}
\newlabel{figOMPLike}
\newlabel{figSemCapture}
\newlabel{fig}
\newlabel{sub@fig:execspace}
\newlabel{sub@fig:memspace}
